//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TLJ001Entities : DbContext
    {
        public TLJ001Entities()
            : base("name=TLJ001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eps> Eps { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual int AddUser(string nombre, string apellido, Nullable<System.DateTime> cumple, Nullable<int> eps)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var cumpleParameter = cumple.HasValue ?
                new ObjectParameter("cumple", cumple) :
                new ObjectParameter("cumple", typeof(System.DateTime));
    
            var epsParameter = eps.HasValue ?
                new ObjectParameter("eps", eps) :
                new ObjectParameter("eps", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", nombreParameter, apellidoParameter, cumpleParameter, epsParameter);
        }
    
        public virtual int DeleteUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", idParameter);
        }
    
        public virtual ObjectResult<SearchAllUser_Result> SearchAllUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchAllUser_Result>("SearchAllUser");
        }
    
        public virtual ObjectResult<SearchUser_Result> SearchUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchUser_Result>("SearchUser", idParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> id, string nombre, string apellido, Nullable<System.DateTime> cumple, Nullable<int> eps)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var cumpleParameter = cumple.HasValue ?
                new ObjectParameter("cumple", cumple) :
                new ObjectParameter("cumple", typeof(System.DateTime));
    
            var epsParameter = eps.HasValue ?
                new ObjectParameter("eps", eps) :
                new ObjectParameter("eps", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", idParameter, nombreParameter, apellidoParameter, cumpleParameter, epsParameter);
        }
    }
}
